// This file is autogenerated -- probably shouldn't modify it by hand

package clobits.sdl.ni;

import clobits.sdl.Keysym;
import clobits.wrappers.IWrapperNI;

public class KeysymWrapper implements Keysym, IWrapperNI {
  IKeysym pointer;

  // used when sending data to native functions
  public IKeysym unwrap() {
    return this.pointer;
  }

  public int sym() {
    return this.pointer.sym();
  }

  public void set_sym(int v) {
    this.pointer.set_sym(v);
  }

  public KeysymWrapper(IKeysym pointer) {
    this.pointer = pointer;
  }
}
