// This file is autogenerated -- probably shouldn't modify it by hand

package bindings.sdl_ni_generated;

import bindings.sdl_structs.ISDL_PixelFormat;
import clobits.all_targets.IWrapper;

public class WrapSDL_PixelFormat implements ISDL_PixelFormat, IWrapper {
  SDL_PixelFormat pointer;

  // used when sending data to native functions
  public SDL_PixelFormat unwrap() {
    return this.pointer;
  }

  public clobits.wrappers.WrapVoid palette() {
    return new clobits.wrappers.WrapVoid(this.pointer.palette());
  }

  public WrapSDL_PixelFormat(SDL_PixelFormat pointer) {
    this.pointer = pointer;
  }
}
