// This file is autogenerated -- probably shouldn't modify it by hand

package bindings.sdl_ni_generated;

import bindings.sdl_structs.ISDL_Surface;
import clobits.all_targets.IWrapper;

public class WrapSDL_Surface implements ISDL_Surface, IWrapper {
  SDL_Surface pointer;

  // used when sending data to native functions
  public SDL_Surface unwrap() {
    return this.pointer;
  }

  public bindings.sdl_ni_generated.SDL_PixelFormat format() {
    return this.pointer.format();
  }

  public WrapSDL_Surface(SDL_Surface pointer) {
    this.pointer = pointer;
  }
}
