;; This file is autogenerated -- probably shouldn't modify it by hand
(clojure.core/ns
 bindings.ncurses-ns
 (:require [clojure.java.io])
 (:import
  org.graalvm.polyglot.Context
  org.graalvm.polyglot.Source
  org.graalvm.polyglot.Value))

(def ^{:private true} empty-array (clojure.core/object-array 0))

(clojure.core/defn
 context-f609
 []
 (clojure.core/->
  (org.graalvm.polyglot.Context/newBuilder
   (clojure.core/into-array ["llvm"]))
  (.allowAllAccess true)
  (.build)))

(clojure.core/defn
 ^{:private true}
 source-f610
 []
 (clojure.core/->
  (org.graalvm.polyglot.Source/newBuilder
   "llvm"
   (if
    (clojure.core/string? "libs/libbindings$ncurses.so")
    (clojure.java.io/file "libs/libbindings$ncurses.so")
    "libs/libbindings$ncurses.so"))
  (.build)))

(def polyglot-context (context-f609))

(def polyglot-lib (.eval polyglot-context (source-f610)))

(def
 ^{:private true}
 silly611
 (.getMember polyglot-lib "_SHADOWING_silly"))

(clojure.core/defn
 silly
 ([arg0] (.executeVoid silly611 (clojure.core/object-array [arg0]))))

(def
 ^{:private true}
 string612
 (.getMember polyglot-lib "_SHADOWING_string"))

(clojure.core/defn
 string
 ([size] (.execute string612 (clojure.core/object-array [size]))))

(def
 ^{:private true}
 other-print-w613
 (.getMember polyglot-lib "_SHADOWING_other_print_w"))

(clojure.core/defn
 other-print-w
 ([value]
  (clojure.core/->
   (.execute other-print-w613 (clojure.core/object-array [value]))
   .asInt)))

(def
 ^{:private true}
 append-char614
 (.getMember polyglot-lib "_SHADOWING_append_char"))

(clojure.core/defn
 append-char
 ([str pos c]
  (.execute append-char614 (clojure.core/object-array [str pos c]))))

(def
 ^{:private true}
 free615
 (.getMember polyglot-lib "_SHADOWING_free"))

(clojure.core/defn
 free
 ([ptr] (.executeVoid free615 (clojure.core/object-array [ptr]))))

(def
 ^{:private true}
 malloc616
 (.getMember polyglot-lib "_SHADOWING_malloc"))

(clojure.core/defn
 malloc
 ([size] (.executeVoid malloc616 (clojure.core/object-array [size]))))

(def
 ^{:private true}
 initscr617
 (.getMember polyglot-lib "_SHADOWING_initscr"))

(clojure.core/defn initscr ([] (.execute initscr617 empty-array)))

(def
 ^{:private true}
 delwin618
 (.getMember polyglot-lib "_SHADOWING_delwin"))

(clojure.core/defn
 delwin
 ([win]
  (clojure.core/->
   (.execute delwin618 (clojure.core/object-array [win]))
   .asInt)))

(def
 ^{:private true}
 endwin619
 (.getMember polyglot-lib "_SHADOWING_endwin"))

(clojure.core/defn
 endwin
 ([] (clojure.core/-> (.execute endwin619 empty-array) .asInt)))

(def
 ^{:private true}
 printw620
 (.getMember polyglot-lib "_SHADOWING_printw"))

(clojure.core/defn
 printw
 ([arg0]
  (clojure.core/->
   (.execute printw620 (clojure.core/object-array [arg0]))
   .asInt)))

(def
 ^{:private true}
 refresh621
 (.getMember polyglot-lib "_SHADOWING_refresh"))

(clojure.core/defn
 refresh
 ([] (clojure.core/-> (.execute refresh621 empty-array) .asInt)))

(def
 ^{:private true}
 wrefresh622
 (.getMember polyglot-lib "_SHADOWING_wrefresh"))

(clojure.core/defn
 wrefresh
 ([win]
  (clojure.core/->
   (.execute wrefresh622 (clojure.core/object-array [win]))
   .asInt)))

