;; This file is autogenerated -- probably shouldn't modify it by hand
(clojure.core/ns
 bindings.ncurses-wrapper
 (:import clobits.all_targets.IWrapperNI)
 (:gen-class))

(clojure.core/defn
 free
 
 [^clobits.all_targets.IWrapperNI ptr]
 (bindings.ncurses/free (.unwrap ptr)))

(clojure.core/defn
 malloc
 ^clobits.wrappers.WrapVoid
 [^long size]
 (new clobits.wrappers.WrapVoid (bindings.ncurses/malloc size)))

(clojure.core/defn
 initscr
 ^clobits.wrappers.WrapVoid
 []
 (new clobits.wrappers.WrapVoid (bindings.ncurses/initscr)))

(clojure.core/defn
 delwin
 ^long
 [^clobits.all_targets.IWrapperNI win]
 (bindings.ncurses/delwin (.unwrap win)))

(clojure.core/defn endwin ^long [] (bindings.ncurses/endwin))

(clojure.core/defn noecho ^long [] (bindings.ncurses/noecho))

(clojure.core/defn
 curs-set
 ^long
 [^long visibility]
 (bindings.ncurses/curs-set visibility))

(clojure.core/defn
 mvprintw
 ^long
 [^long y ^long x ^clobits.all_targets.IWrapperNI fmt]
 (bindings.ncurses/mvprintw y x (.unwrap fmt)))

(clojure.core/defn clear ^long [] (bindings.ncurses/clear))

(clojure.core/defn
 getmaxx
 ^long
 [^clobits.all_targets.IWrapperNI win]
 (bindings.ncurses/getmaxx (.unwrap win)))

(clojure.core/defn
 getmaxy
 ^long
 [^clobits.all_targets.IWrapperNI win]
 (bindings.ncurses/getmaxy (.unwrap win)))

(clojure.core/defn
 getmaxyx
 
 [^clobits.all_targets.IWrapperNI win ^long y ^long x]
 (bindings.ncurses/getmaxyx (.unwrap win) y x))

(clojure.core/defn
 printw
 ^long
 [^clobits.all_targets.IWrapperNI arg0]
 (bindings.ncurses/printw (.unwrap arg0)))

(clojure.core/defn refresh ^long [] (bindings.ncurses/refresh))

(clojure.core/defn
 wrefresh
 ^long
 [^clobits.all_targets.IWrapperNI win]
 (bindings.ncurses/wrefresh (.unwrap win)))

