;; This file is autogenerated -- probably shouldn't modify it by hand
(clojure.core/ns
 clobits.sdl.ni.generate
 (:require [clobits.patch-gen-class] [clobits.all-targets])
 (:import
  org.graalvm.word.PointerBase
  org.graalvm.nativeimage.c.struct.CField
  org.graalvm.nativeimage.c.CContext
  org.graalvm.nativeimage.c.function.CFunction
  org.graalvm.nativeimage.c.function.CLibrary
  org.graalvm.nativeimage.c.struct.CFieldAddress
  org.graalvm.nativeimage.c.struct.CStruct
  org.graalvm.nativeimage.c.struct.AllowWideningCast
  org.graalvm.nativeimage.c.function.CFunction
  org.graalvm.word.WordFactory
  clobits.all_targets.IVoidPointer
  [org.graalvm.nativeimage.c.type CCharPointer VoidPointer])
 (:gen-class))

(clojure.core/deftype
 Headers
 []
 org.graalvm.nativeimage.c.CContext$Directives
 (getHeaderFiles
  [_]
  ["\"/Users/test/programmering/clojure/clobits/example-src/clobits/sdl.h\""]))

(clojure.core/gen-interface
 :name
 ^{org.graalvm.nativeimage.c.CContext clobits.sdl.ni.generate.Headers, org.graalvm.nativeimage.c.function.CLibrary "clobits$sdl-ni", org.graalvm.nativeimage.c.struct.CStruct "SDL_Event"}
 clobits.sdl.ni.IEvent
 :extends
 [org.graalvm.word.PointerBase clobits.sdl.Event]
 :methods
 [[^{org.graalvm.nativeimage.c.struct.CField "type"} type [] int]
  [^{org.graalvm.nativeimage.c.struct.CField "type"}
   set_type
   [int]
   void]
  [^{org.graalvm.nativeimage.c.struct.CFieldAddress "key"}
   key
   []
   clobits.sdl.ni.IKeyboardEvent]])

(clojure.core/gen-interface
 :name
 ^{org.graalvm.nativeimage.c.CContext clobits.sdl.ni.generate.Headers, org.graalvm.nativeimage.c.function.CLibrary "clobits$sdl-ni", org.graalvm.nativeimage.c.struct.CStruct "SDL_KeyboardEvent"}
 clobits.sdl.ni.IKeyboardEvent
 :extends
 [org.graalvm.word.PointerBase clobits.sdl.KeyboardEvent]
 :methods
 [[^{org.graalvm.nativeimage.c.struct.CFieldAddress "keysym"}
   keysym
   []
   clobits.sdl.ni.IKeysym]])

(clojure.core/gen-interface
 :name
 ^{org.graalvm.nativeimage.c.CContext clobits.sdl.ni.generate.Headers, org.graalvm.nativeimage.c.function.CLibrary "clobits$sdl-ni", org.graalvm.nativeimage.c.struct.CStruct "SDL_Keysym"}
 clobits.sdl.ni.IKeysym
 :extends
 [org.graalvm.word.PointerBase clobits.sdl.Keysym]
 :methods
 [[^{org.graalvm.nativeimage.c.struct.CField "sym"} sym [] int]
  [^{org.graalvm.nativeimage.c.struct.CField "sym"}
   set_sym
   [int]
   void]])

(clojure.core/gen-interface
 :name
 ^{org.graalvm.nativeimage.c.CContext clobits.sdl.ni.generate.Headers, org.graalvm.nativeimage.c.function.CLibrary "clobits$sdl-ni", org.graalvm.nativeimage.c.struct.CStruct "SDL_Surface"}
 clobits.sdl.ni.ISurface
 :extends
 [org.graalvm.word.PointerBase clobits.sdl.Surface]
 :methods
 [[^{org.graalvm.nativeimage.c.struct.CField "format"}
   format
   []
   clobits.sdl.ni.IPixelFormat]
  [^{org.graalvm.nativeimage.c.struct.CField "format"}
   set_format
   [clobits.sdl.ni.IPixelFormat]
   void]])

(clojure.core/gen-interface
 :name
 ^{org.graalvm.nativeimage.c.CContext clobits.sdl.ni.generate.Headers, org.graalvm.nativeimage.c.function.CLibrary "clobits$sdl-ni", org.graalvm.nativeimage.c.struct.CStruct "SDL_PixelFormat"}
 clobits.sdl.ni.IPixelFormat
 :extends
 [org.graalvm.word.PointerBase clobits.sdl.PixelFormat]
 :methods
 [[^{org.graalvm.nativeimage.c.struct.CField "palette"}
   palette
   []
   clobits.all_targets.IVoidPointer]
  [^{org.graalvm.nativeimage.c.struct.CField "palette"}
   set_palette
   [clobits.all_targets.IVoidPointer]
   void]])

(clojure.core/gen-interface
 :name
 ^{org.graalvm.nativeimage.c.CContext clobits.sdl.ni.generate.Headers, org.graalvm.nativeimage.c.function.CLibrary "clobits$sdl-ni", org.graalvm.nativeimage.c.struct.CStruct "SDL_Rect"}
 clobits.sdl.ni.IRect
 :extends
 [org.graalvm.word.PointerBase clobits.sdl.Rect]
 :methods
 [[^{org.graalvm.nativeimage.c.struct.CField "x"} x [] int]
  [^{org.graalvm.nativeimage.c.struct.CField "x"} set_x [int] void]
  [^{org.graalvm.nativeimage.c.struct.CField "y"} y [] int]
  [^{org.graalvm.nativeimage.c.struct.CField "y"} set_y [int] void]
  [^{org.graalvm.nativeimage.c.struct.CField "w"} w [] int]
  [^{org.graalvm.nativeimage.c.struct.CField "w"} set_w [int] void]
  [^{org.graalvm.nativeimage.c.struct.CField "h"} h [] int]
  [^{org.graalvm.nativeimage.c.struct.CField "h"} set_h [int] void]])

(clobits.patch-gen-class/gen-class-native
 :name
 ^{org.graalvm.nativeimage.c.CContext clobits.sdl.ni.generate.Headers, org.graalvm.nativeimage.c.function.CLibrary "clobits$sdl-ni"}
 clobits.sdl.ni.interop
 :methods
 [^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_GET_SDL_INIT_VIDEO"}}
   get_sdl_init_video
   []
   int]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_GET_SDL_WINDOW_SHOWN"}}
   get_sdl_window_shown
   []
   int]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_get_null"}}
   get_null
   []
   clobits.all_targets.IVoidPointer]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_gen_title"}}
   gen_title
   []
   org.graalvm.nativeimage.c.type.CCharPointer]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_create_rect"}}
   create_rect
   [int int int int]
   clobits.sdl.ni.IRect]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_get_e"}}
   get_e
   []
   clobits.sdl.ni.IEvent]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_SDL_Init"}}
   init
   [int]
   int]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_SDL_PollEvent"}}
   poll_event
   [clobits.sdl.ni.IEvent]
   int]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_SDL_Delay"}}
   delay
   [int]
   void]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_SDL_UpdateWindowSurface"}}
   update_window_surface
   [org.graalvm.nativeimage.c.type.VoidPointer]
   int]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_SDL_GetWindowSurface"}}
   get_window_surface
   [org.graalvm.nativeimage.c.type.VoidPointer]
   clobits.sdl.ni.ISurface]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_SDL_MapRGB"}}
   map_rgb
   [clobits.sdl.ni.IPixelFormat int int int]
   int]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_SDL_CreateWindow"}}
   create_window
   [org.graalvm.nativeimage.c.type.CCharPointer int int int int int]
   clobits.all_targets.IVoidPointer]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_SDL_FillRect"}}
   fill_rect
   [clobits.sdl.ni.ISurface clobits.sdl.ni.IRect int]
   int]
  ^{:static true, :native true}
  [^{org.graalvm.nativeimage.c.function.CFunction {:transition org.graalvm.nativeimage.c.function.CFunction$Transition/NO_TRANSITION, :value "_SHADOWING_SDL_Quit"}}
   quit
   []
   void]])

