// This file is autogenerated -- probably shouldn't modify it by hand

package clobits.sdl.ni;

import clobits.sdl.PixelFormat;
import clobits.all_targets.IWrapperNI;

public class PixelFormatWrapper implements PixelFormat, IWrapperNI {
  IPixelFormat pointer;

  // used when sending data to native functions
  public IPixelFormat unwrap() {
    return this.pointer;
  }

  public clobits.wrappers.WrapVoid palette() {
    return new clobits.wrappers.WrapVoid(this.pointer.palette());
  }

  public void set_palette(clobits.wrappers.WrapVoid v) {
    this.pointer.set_palette(v.unwrap());
  }

  public void set_palette(clobits.all_targets.IVoidPointerYE v) {
    this.pointer.set_palette(v);
  }

  public PixelFormatWrapper(IPixelFormat pointer) {
    this.pointer = pointer;
  }
}
