// This file is autogenerated -- probably shouldn't modify it by hand

package clobits.sdl.ni;

import clobits.sdl.Event;
import clobits.wrappers.IWrapperNI;

public class EventWrapper implements Event, IWrapperNI {
  IEvent pointer;

  // used when sending data to native functions
  public IEvent unwrap() {
    return this.pointer;
  }

  public int type() {
    return this.pointer.type();
  }

  public clobits.sdl.ni.KeyboardEventWrapper key() {
    return new clobits.sdl.ni.KeyboardEventWrapper(this.pointer.key());
  }

  public void set_type(int v) {
    this.pointer.set_type(v);
  }

  public void set_key(clobits.sdl.ni.KeyboardEventWrapper v) {
    this.pointer.set_key(v.unwrap());
  }

  public void set_key(clobits.sdl.KeyboardEvent v) {
    this.pointer.set_key(v);
  }

  public EventWrapper(IEvent pointer) {
    this.pointer = pointer;
  }
}
