// This file is autogenerated -- probably shouldn't modify it by hand

package clobits.sdl.ni;

import clobits.sdl.KeyboardEvent;
import clobits.wrappers.IWrapperNI;

public class KeyboardEventWrapper implements KeyboardEvent, IWrapperNI {
  IKeyboardEvent pointer;

  // used when sending data to native functions
  public IKeyboardEvent unwrap() {
    return this.pointer;
  }

  public clobits.sdl.ni.KeysymWrapper keysym() {
    return new clobits.sdl.ni.KeysymWrapper(this.pointer.keysym());
  }

  public void set_keysym(clobits.sdl.ni.KeysymWrapper v) {
    this.pointer.set_keysym(v.unwrap());
  }

  public void set_keysym(clobits.sdl.Keysym v) {
    this.pointer.set_keysym(v);
  }

  public KeyboardEventWrapper(IKeyboardEvent pointer) {
    this.pointer = pointer;
  }
}
