// This file is autogenerated -- probably shouldn't modify it by hand

package clobits.sdl.ni;

import clobits.sdl.Rect;
import clobits.wrappers.IWrapperNI;

public class RectWrapper implements Rect, IWrapperNI {
  IRect pointer;

  // used when sending data to native functions
  public IRect unwrap() {
    return this.pointer;
  }

  public int x() {
    return this.pointer.x();
  }

  public int y() {
    return this.pointer.y();
  }

  public int w() {
    return this.pointer.w();
  }

  public int h() {
    return this.pointer.h();
  }

  public void set_x(int v) {
    this.pointer.set_x(v);
  }

  public void set_y(int v) {
    this.pointer.set_y(v);
  }

  public void set_w(int v) {
    this.pointer.set_w(v);
  }

  public void set_h(int v) {
    this.pointer.set_h(v);
  }

  public RectWrapper(IRect pointer) {
    this.pointer = pointer;
  }
}
