;; This file is autogenerated by clobits -- probably shouldn't modify it by hand
(clojure.core/ns clobits.sdl.structs)

(clojure.core/gen-interface
 :name
 ^{org.graalvm.polyglot.HostAccess$Implementable true}
 clobits.sdl.Event
 :methods
 [[type [] int]
  [set_type [int] void]
  [key [] clobits.sdl.KeyboardEvent]
  [set_key [clobits.sdl.KeyboardEvent] void]])

(clojure.core/gen-interface
 :name
 ^{org.graalvm.polyglot.HostAccess$Implementable true}
 clobits.sdl.KeyboardEvent
 :methods
 [[keysym [] clobits.sdl.Keysym]
  [set_keysym [clobits.sdl.Keysym] void]])

(clojure.core/gen-interface
 :name
 ^{org.graalvm.polyglot.HostAccess$Implementable true}
 clobits.sdl.Keysym
 :methods
 [[sym [] int] [set_sym [int] void]])

(clojure.core/gen-interface
 :name
 ^{org.graalvm.polyglot.HostAccess$Implementable true}
 clobits.sdl.Surface
 :methods
 [[format [] clobits.sdl.PixelFormat]
  [set_format [clobits.sdl.PixelFormat] void]])

(clojure.core/gen-interface
 :name
 ^{org.graalvm.polyglot.HostAccess$Implementable true}
 clobits.sdl.PixelFormat
 :methods
 [[palette [] clobits.wrappers.IVoidPointerYE]
  [set_palette [clobits.wrappers.IVoidPointerYE] void]])

(clojure.core/gen-interface
 :name
 ^{org.graalvm.polyglot.HostAccess$Implementable true}
 clobits.sdl.Rect
 :methods
 [[x [] int]
  [set_x [int] void]
  [y [] int]
  [set_y [int] void]
  [w [] int]
  [set_w [int] void]
  [h [] int]
  [set_h [int] void]])

