// This file is autogenerated -- probably shouldn't modify it by hand

package bindings.sdl_ni_generated;

import bindings.sdl_structs.ISDL_Keysym;
import clobits.all_targets.IWrapperNI;

public class WrapSDL_Keysym implements ISDL_Keysym, IWrapperNI {
  SDL_Keysym pointer;

  // used when sending data to native functions
  public SDL_Keysym unwrap() {
    return this.pointer;
  }

  public int sym() {
    return this.pointer.sym();
  }

  public void set_sym(int v) {
    this.pointer.set_sym(v);
  }

  public WrapSDL_Keysym(SDL_Keysym pointer) {
    this.pointer = pointer;
  }
}
