// This file is autogenerated -- probably shouldn't modify it by hand

package bindings.sdl_ni_generated;

import bindings.sdl_structs.ISDL_Rect;
import clobits.all_targets.IWrapperNI;

public class WrapSDL_Rect implements ISDL_Rect, IWrapperNI {
  SDL_Rect pointer;

  // used when sending data to native functions
  public SDL_Rect unwrap() {
    return this.pointer;
  }

  public int x() {
    return this.pointer.x();
  }

  public int y() {
    return this.pointer.y();
  }

  public int w() {
    return this.pointer.w();
  }

  public int h() {
    return this.pointer.h();
  }

  public void set_x(int v) {
    this.pointer.set_x(v);
  }

  public void set_y(int v) {
    this.pointer.set_y(v);
  }

  public void set_w(int v) {
    this.pointer.set_w(v);
  }

  public void set_h(int v) {
    this.pointer.set_h(v);
  }

  public WrapSDL_Rect(SDL_Rect pointer) {
    this.pointer = pointer;
  }
}
